# Generated by Django 5.2 on 2025-05-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketclass',
            name='seat_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
