# Generated by Django 5.2 on 2025-05-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_ticketclass_seat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketclass',
            name='seat_name',
        ),
    ]
