# Generated by Django 5.2 on 2025-05-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_ticketclass_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['booked_at']},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_class',
        ),
    ]
