# Generated by Django 5.2 on 2025-05-04 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_ticket_options_remove_ticket_ticket_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['ticket_class', 'booked_at']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ticketclass'),
        ),
    ]
