# Generated by Django 5.2 on 2025-05-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_ticket_options_ticket_ticket_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
    ]
