# Generated by Django 5.2 on 2025-05-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'start_time')},
        ),
    ]
