# Generated by Django 5.2 on 2025-05-05 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
