# Generated by Django 5.2 on 2025-05-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_chatmessage_sent_at_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'event')},
        ),
    ]
