# Generated by Django 5.2 on 2025-05-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_ticket_checkin_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='checked_in',
            new_name='is_checked_in',
        ),
    ]
